 Multivariate Linear regression in machine learning is an extenstion of linear regession when mutiple independent variables are used to predict a single dependent variable. The releationship between the independent variable and the dependent variable is Represented by Linear Equation 

Here area, bedrooms, age are called the independant variable or features whereas price is a dependant Variable

In [17]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from sklearn import linear_model

In [18]:
df = pd.read_csv("homeprices 2 (1).csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Data pre processing: Fill NA Values with median value of a column

In [19]:
df.bedrooms.median()

4.0

In [20]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [21]:
reg = linear_model.LinearRegression()
reg.fit(df.drop("price", axis = "columns"), df.price)

LinearRegression()

In [22]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [23]:
reg.intercept_

221323.00186540402

In [24]:
reg.score

<bound method RegressorMixin.score of LinearRegression()>

In [27]:
reg

LinearRegression()

Find the price of home with 3000 sqr ft area, 3bedroom, 40 years old

In [26]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [28]:
reg.predict([[40,3,3000]])

array([-9399181.58612199])

Find the price of home with 2500 sqr ft area, 4 bedroom, 5 years old 

In [29]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In exercise folder  **hiring.csv**. The data  contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,
**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**